"""Create added colums to courses

Revision ID: 71e4df707a8f
Revises: 1f9f9d1ec766
Create Date: 2023-05-27 02:46:43.460902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e4df707a8f'
down_revision = '1f9f9d1ec766'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('badge_url', sa.String(length=255), nullable=False))
    op.add_column('courses', sa.Column('first_class_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'first_class_url')
    op.drop_column('courses', 'badge_url')
    # ### end Alembic commands ###
