"""Drop column backup_url

Revision ID: f3d96845189a
Revises: 71e4df707a8f
Create Date: 2023-06-04 15:04:48.101250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d96845189a'
down_revision = '71e4df707a8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'backup_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('backup_url', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
